# Generated by Django 4.0.6 on 2022-08-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='murojaat',
            name='matni',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='murojaat',
            name='qayerga',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
