# Generated by Django 4.0.6 on 2022-08-02 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_murojaat_matni_alter_murojaat_qayerga'),
    ]

    operations = [
        migrations.AddField(
            model_name='murojaat',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
